In [50]:
import pandas as pd

import numpy as np

from sklearn.preprocessing import StandardScaler, LabelEncoder

In [51]:
df = pd.read_csv("Loan Approval Prediction.csv")

df.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
0,22.0,71948.0,0,35000.0,16.02,0.49,3.0,561,0,0,...,0,0,1,0,0,0,1,0,0,1
1,21.0,12282.0,0,1000.0,11.14,0.08,2.0,504,0,0,...,0,1,0,1,0,0,0,0,1,0
2,25.0,12438.0,3,5500.0,12.87,0.44,3.0,635,0,0,...,0,0,0,0,0,1,0,0,0,1
3,23.0,79753.0,0,35000.0,15.23,0.44,2.0,675,0,1,...,0,0,1,0,0,1,0,0,0,1
4,24.0,66135.0,1,35000.0,14.27,0.53,4.0,586,1,0,...,0,0,1,0,0,1,0,0,0,1

In [52]:
print(df.shape)

df.info()

(70000, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 23 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   person_age                          70000 non-null  float64
 1   person_income                       70000 non-null  float64
 2   person_emp_exp                      70000 non-null  int64
 3   loan_amnt                           70000 non-null  float64
 4   loan_int_rate                       70000 non-null  float64
 5   loan_percent_income                 70000 non-null  float64
 6   cb_person_cred_hist_length          70000 non-null  float64
 7   credit_score                        70000 non-null  int64
 8   person_gender_male                  70000 non-null  int64
 9   person_education_Bachelor           70000 non-null  int64
 10  person_education_Doctorate          70000 non-null  int64
 11  person_education_High School        70000 non-null  int64
 12  person_education_Master             70000 non-null  int64
 13  person_home_ownership_OTHER         70000 non-null  int64
 14  person_home_ownership_OWN           70000 non-null  int64
 15  person_home_ownership_RENT          70000 non-null  int64
 16  loan_intent_EDUCATION               70000 non-null  int64
 17  loan_intent_HOMEIMPROVEMENT         70000 non-null  int64
 18  loan_intent_MEDICAL                 70000 non-null  int64
 19  loan_intent_PERSONAL                70000 non-null  int64
 20  loan_intent_VENTURE                 70000 non-null  int64
 21  previous_loan_defaults_on_file_Yes  70000 non-null  int64
 22  loan_status                         70000 non-null  int64
dtypes: float64(6), int64(17)
memory usage: 12.3 MB

In [53]:
df.isnull().sum()

person_age                            0
person_income                         0
person_emp_exp                        0
loan_amnt                             0
loan_int_rate                         0
loan_percent_income                   0
cb_person_cred_hist_length            0
credit_score                          0
person_gender_male                    0
person_education_Bachelor             0
person_education_Doctorate            0
person_education_High School          0
person_education_Master               0
person_home_ownership_OTHER           0
person_home_ownership_OWN             0
person_home_ownership_RENT            0
loan_intent_EDUCATION                 0
loan_intent_HOMEIMPROVEMENT           0
loan_intent_MEDICAL                   0
loan_intent_PERSONAL                  0
loan_intent_VENTURE                   0
previous_loan_defaults_on_file_Yes    0
loan_status                           0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(7)

In [55]:
df = df.drop_duplicates()

df.shape

(69993, 23)

In [56]:
df.describe()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
count,69993.000000,6.999300e+04,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,...,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000,69993.000000
mean,27.673053,7.298166e+04,5.161116,10020.839884,11.672888,0.162007,5.826568,632.424000,0.463203,0.225594,...,0.001814,0.043947,0.559870,0.145600,0.078394,0.151458,0.121026,0.120055,0.326576,0.499950
std,5.692132,7.056723e+04,5.677094,6623.828849,3.005889,0.099094,3.688024,47.342739,0.498648,0.417976,...,0.042558,0.204979,0.496406,0.352708,0.268792,0.358497,0.326160,0.325028,0.468964,0.500004
min,20.000000,8.000000e+03,0.000000,500.000000,5.420000,0.000000,2.000000,390.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,4.175600e+04,1.000000,5000.000000,9.750000,0.080000,3.000000,603.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,26.000000,6.103000e+04,4.000000,8458.000000,11.490000,0.140000,4.000000,638.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,30.000000,8.757300e+04,7.000000,14000.000000,13.860000,0.230000,8.000000,667.000000,1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,144.000000,7.200766e+06,125.000000,35000.000000,20.000000,0.660000,30.000000,850.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [57]:
X = df.drop("loan_status", axis=1)
y = df["loan_status"]

In [58]:
#puts numerical features on a similar scale

numerical_columns = X.select_dtypes(include=["int64", "float64"]).columns
scaler = StandardScaler()
X[numerical_columns] = scaler.fit_transform(X[numerical_columns])
X.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_education_Master,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes
0,-0.996655,-0.014648,-0.909119,3.771133,1.446209,3.309960,-0.766424,-1.508669,-0.928926,-0.539734,...,2.871603,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,-0.422483,2.694932,-0.36937,-0.696382
1,-1.172338,-0.860174,-0.909119,-1.361887,-0.177283,-0.827572,-1.037573,-2.712663,-0.928926,-0.539734,...,-0.348238,-0.042635,4.664177,-1.127855,2.42242,-0.291654,-0.422483,-0.371067,-0.36937,1.435994
2,-0.469608,-0.857963,-0.380676,-0.682516,0.398258,2.805382,-0.766424,0.054412,-0.928926,-0.539734,...,-0.348238,-0.042635,-0.214400,-1.127855,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382
3,-0.820973,0.095957,-0.909119,3.771133,1.183389,2.805382,-1.037573,0.899321,-0.928926,1.852766,...,-0.348238,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382
4,-0.645291,-0.097024,-0.732971,3.771133,0.864014,3.713621,-0.495274,-0.980601,1.076512,-0.539734,...,2.871603,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382

In [59]:
# Combine into one dataset
processed_df = pd.concat([X, y], axis=1)
processed_df.head()

,person_age,person_income,person_emp_exp,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,person_gender_male,person_education_Bachelor,...,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,previous_loan_defaults_on_file_Yes,loan_status
0,-0.996655,-0.014648,-0.909119,3.771133,1.446209,3.309960,-0.766424,-1.508669,-0.928926,-0.539734,...,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,-0.422483,2.694932,-0.36937,-0.696382,1
1,-1.172338,-0.860174,-0.909119,-1.361887,-0.177283,-0.827572,-1.037573,-2.712663,-0.928926,-0.539734,...,-0.042635,4.664177,-1.127855,2.42242,-0.291654,-0.422483,-0.371067,-0.36937,1.435994,0
2,-0.469608,-0.857963,-0.380676,-0.682516,0.398258,2.805382,-0.766424,0.054412,-0.928926,-0.539734,...,-0.042635,-0.214400,-1.127855,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382,1
3,-0.820973,0.095957,-0.909119,3.771133,1.183389,2.805382,-1.037573,0.899321,-0.928926,1.852766,...,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382,1
4,-0.645291,-0.097024,-0.732971,3.771133,0.864014,3.713621,-0.495274,-0.980601,1.076512,-0.539734,...,-0.042635,-0.214400,0.886639,-0.41281,-0.291654,2.366958,-0.371067,-0.36937,-0.696382,1

In [60]:
print(processed_df.shape)
print(processed_df.columns.tolist())

(69993, 23)
['person_age', 'person_income', 'person_emp_exp', 'loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'person_gender_male', 'person_education_Bachelor', 'person_education_Doctorate', 'person_education_High School', 'person_education_Master', 'person_home_ownership_OTHER', 'person_home_ownership_OWN', 'person_home_ownership_RENT', 'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT', 'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE', 'previous_loan_defaults_on_file_Yes', 'loan_status']

In [61]:
# Save the processed dataset
processed_df.to_csv("processed_loan_approval.csv", index=False)

# Save the scaler
import pickle

with open("loan_approval_scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

print("Dataset 1 preprocessing saved!")

Dataset 1 preprocessing saved!

## Dataset 2

In [62]:
df2=pd.read_csv("loan_data.csv")

In [63]:
df2.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [64]:
print(df2.shape)

df2.info()

(45000, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  object
 2   person_education                45000 non-null  object
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  object
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  object
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  object
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 4.8+ MB

In [65]:
df2.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
cb_person_cred_hist_length        0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [66]:
df2.duplicated().sum()

np.int64(0)

In [67]:
# Find columns that contain text/categorical values
categorical_columns = df2.select_dtypes(include=["object"]).columns

print("Categorical columns:")
print(categorical_columns)

Categorical columns:
Index(['person_gender', 'person_education', 'person_home_ownership',
       'loan_intent', 'previous_loan_defaults_on_file'],
      dtype='object')

In [68]:
label_encoder = LabelEncoder()

for column in categorical_columns:
    df2[column] = label_encoder.fit_transform(df2[column])

df2.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,4,71948.0,0,3,35000.0,4,16.02,0.49,3.0,561,0,1
1,21.0,0,3,12282.0,0,2,1000.0,1,11.14,0.08,2.0,504,1,0
2,25.0,0,3,12438.0,3,0,5500.0,3,12.87,0.44,3.0,635,0,1
3,23.0,0,1,79753.0,0,3,35000.0,3,15.23,0.44,2.0,675,0,1
4,24.0,1,4,66135.0,1,3,35000.0,3,14.27,0.53,4.0,586,0,1

In [69]:
# Check the data types after encoding
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  int64
 2   person_education                45000 non-null  int64
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  int64
 5   person_home_ownership           45000 non-null  int64
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  int64
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  int64
 12  previous_loan_defaults_on_file  45000 non-null  int64
 13  loan_status                     45000 non-null  int64
dtypes: float64(6), int64(8)
memory usage: 4.8 MB

In [70]:
df2.describe()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
count,45000.000000,45000.000000,45000.000000,4.500000e+04,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000,45000.000000
mean,27.764178,0.552022,1.743933,8.031905e+04,5.410333,1.696622,9583.157556,2.525911,11.006606,0.139725,5.867489,632.608756,0.507956,0.222222
std,6.045108,0.497292,1.479148,8.042250e+04,6.063532,1.440497,6314.886691,1.728305,2.978808,0.087212,3.879702,50.435865,0.499942,0.415744
min,20.000000,0.000000,0.000000,8.000000e+03,0.000000,0.000000,500.000000,0.000000,5.420000,0.000000,2.000000,390.000000,0.000000,0.000000
25%,24.000000,0.000000,0.000000,4.720400e+04,1.000000,0.000000,5000.000000,1.000000,8.590000,0.070000,3.000000,601.000000,0.000000,0.000000
50%,26.000000,1.000000,1.000000,6.704800e+04,4.000000,3.000000,8000.000000,3.000000,11.010000,0.120000,4.000000,640.000000,1.000000,0.000000
75%,30.000000,1.000000,3.000000,9.578925e+04,8.000000,3.000000,12237.250000,4.000000,12.990000,0.190000,8.000000,670.000000,1.000000,0.000000
max,144.000000,1.000000,4.000000,7.200766e+06,125.000000,3.000000,35000.000000,5.000000,20.000000,0.660000,30.000000,850.000000,1.000000,1.000000

In [71]:
X = df2.drop("loan_status", axis=1)
y = df2["loan_status"]

In [72]:
numerical_columns = X.columns

scaler = StandardScaler()

X[numerical_columns] = scaler.fit_transform(X[numerical_columns])

X.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file
0,-0.953538,-1.110069,1.525264,-0.104090,-0.892284,0.904822,4.024953,0.852919,1.683039,4.016394,-0.739109,-1.419814,-1.016040
1,-1.118963,-1.110069,0.849192,-0.846005,-0.892284,0.210609,-1.359209,-0.882904,0.044782,-0.684829,-0.996863,-2.549975,0.984213
2,-0.457264,-1.110069,0.849192,-0.844065,-0.397517,-1.177817,-0.646600,0.274312,0.625557,3.443074,-0.739109,0.047412,-1.016040
3,-0.788113,-1.110069,-0.502953,-0.007039,-0.892284,0.904822,4.024953,0.274312,1.417829,3.443074,-0.996863,0.840507,-1.016040
4,-0.622689,0.900845,1.525264,-0.176371,-0.727362,0.904822,4.024953,0.274312,1.095549,4.475050,-0.481354,-0.924130,-1.016040

In [73]:
# Add the target column back to the processed features
processed_df2 = pd.concat([X, y], axis=1)

# Display the final preprocessed dataset
processed_df2.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,-0.953538,-1.110069,1.525264,-0.104090,-0.892284,0.904822,4.024953,0.852919,1.683039,4.016394,-0.739109,-1.419814,-1.016040,1
1,-1.118963,-1.110069,0.849192,-0.846005,-0.892284,0.210609,-1.359209,-0.882904,0.044782,-0.684829,-0.996863,-2.549975,0.984213,0
2,-0.457264,-1.110069,0.849192,-0.844065,-0.397517,-1.177817,-0.646600,0.274312,0.625557,3.443074,-0.739109,0.047412,-1.016040,1
3,-0.788113,-1.110069,-0.502953,-0.007039,-0.892284,0.904822,4.024953,0.274312,1.417829,3.443074,-0.996863,0.840507,-1.016040,1
4,-0.622689,0.900845,1.525264,-0.176371,-0.727362,0.904822,4.024953,0.274312,1.095549,4.475050,-0.481354,-0.924130,-1.016040,1

In [74]:
print(processed_df2.shape)
processed_df2.info()

processed_df2.to_csv("processed_loan_data.csv", index=False)

# Save the scaler and encoders
assets = {
    "scaler": scaler,
    "encoders": label_encoder,
    "feature_names": list(X.columns)
}

with open("loan_data_preprocessing.pkl", "wb") as f:
    pickle.dump(assets, f)

print("Dataset 2 preprocessing saved!")

(45000, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_age                      45000 non-null  float64
 1   person_gender                   45000 non-null  float64
 2   person_education                45000 non-null  float64
 3   person_income                   45000 non-null  float64
 4   person_emp_exp                  45000 non-null  float64
 5   person_home_ownership           45000 non-null  float64
 6   loan_amnt                       45000 non-null  float64
 7   loan_intent                     45000 non-null  float64
 8   loan_int_rate                   45000 non-null  float64
 9   loan_percent_income             45000 non-null  float64
 10  cb_person_cred_hist_length      45000 non-null  float64
 11  credit_score                    45000 non-null  float64
 12  previous_loan_defaults_on_file  45000 non-null  float64
 13  loan_status                     45000 non-null  int64
dtypes: float64(13), int64(1)
memory usage: 4.8 MB

Dataset 2 preprocessing saved!